export const DEFAULT_SCHOOL = "nus";

const NUS_HOSTS = ["nus.edu.sg", "www.nus.edu.sg", "enterprise.nus.edu.sg"];
const GOVTECH_HOSTS = ["tech.gov.sg", "www.tech.gov.sg"];
const DSTA_HOSTS = ["dsta.gov.sg", "www.dsta.gov.sg"];
const SGINNOVATE_HOSTS = [
  "sginnovate.com",
  "www.sginnovate.com",
  "central.sginnovate.com",
];
const NYC_HOSTS = [
  "nyc.gov.sg",
  "www.nyc.gov.sg",
  "youthcorps.nyc.gov.sg",
  "discover.nyc.gov.sg",
  "oursggrants.gov.sg",
];
const ASTAR_HOSTS = ["a-star.edu.sg", "www.a-star.edu.sg"];
const PIER71_HOSTS = ["pier71.sg", "www.pier71.sg"];
const CYBERSG_HOSTS = ["tig.cybersg.sg", "ice71.sg"];

export const SOURCE_PRIORITIES = {
  NUS_WEBSITE: 1,
  NUS_OUTLOOK: 1,
  EXTERNAL_PUBLIC: 3,
};

function isNusHost(host) {
  return host === "nus.edu.sg" || host.endsWith(".nus.edu.sg");
}

function inferSourcePriority(source) {
  if (source.type === "public_web" && source.allowedHosts?.some(isNusHost)) {
    return SOURCE_PRIORITIES.NUS_WEBSITE;
  }

  if (source.type === "outlook_mailbox") {
    return SOURCE_PRIORITIES.NUS_OUTLOOK;
  }

  return SOURCE_PRIORITIES.EXTERNAL_PUBLIC;
}

export const OUTLOOK_SEARCH_KEYWORDS = [
  "noc",
  "internship",
  "research assistant",
  "research attachment",
  "summer programme",
  "summer program",
  "winter programme",
  "exchange",
  "student exchange",
  "sep",
  "steer",
  "study trip",
  "competition",
  "hackathon",
  "scholarship",
  "fellowship",
  "mentorship",
  "networking",
  "volunteer",
  "startup",
  "entrepreneurship",
  "applications open",
  "apply now",
  "registration open",
  "deadline",
];

// "school: nus" means the opportunity should be suitable for NUS students.
// It does not mean the opportunity must be hosted by NUS. External organisers
// can be added here as public_web sources with their own allowedHosts.
const crawlerSourceConfig = [
  {
    id: "nus-outlook-user-mailbox",
    school: DEFAULT_SCHOOL,
    type: "outlook_mailbox",
    name: "Connected NUS Outlook mailbox",
    enabled: true,
    searchKeywords: OUTLOOK_SEARCH_KEYWORDS,
    defaultCategory: "other",
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
  },
  {
    id: "nus-cfg-students",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Centre for Future-ready Graduates",
    url: "https://nus.edu.sg/cfg/students#find-jobs-&-internships",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "internship",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    maxLinkedPages: 6,
  },
  {
    id: "nus-gro-student-exchange",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Student Exchange",
    url: "https://www.nus.edu.sg/gro/global-programmes/student-exchange",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "exchange",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    // This page is a directory. Only individual host-university information
    // sheets should become opportunity candidates.
    createRootDocument: false,
    linkedDocumentTypes: ["pdf"],
    programmeDetails: true,
    maxLinkedPages: 60,
  },
  {
    id: "nus-gro-sep-partner-universities",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - SEP Partner Universities",
    url: "https://www.nus.edu.sg/gro/global-programmes/student-exchange/partner-universities",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "exchange",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    createRootDocument: false,
    linkedDocumentTypes: ["pdf"],
    programmeDetails: true,
    maxLinkedPages: 60,
  },
  {
    id: "nus-gro-summer-winter",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Summer and Winter Programmes",
    url: "https://www.nus.edu.sg/gro/global-programmes/summer-and-winter-programmes",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "summer_programme",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    createRootDocument: false,
    linkedDocumentTypes: ["pdf"],
    programmeDetails: true,
    maxLinkedPages: 60,
  },
  {
    id: "nus-gro-summer-partner-universities",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Summer Partner Universities",
    url: "https://www.nus.edu.sg/gro/global-programmes/summer-and-winter-programmes/summer-partner-universities",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "summer_programme",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    createRootDocument: false,
    linkedDocumentTypes: ["pdf"],
    programmeDetails: true,
    maxLinkedPages: 60,
  },
  {
    id: "nus-gro-winter-partner-universities",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Winter Partner Universities",
    url: "https://www.nus.edu.sg/gro/global-programmes/summer-and-winter-programmes/winter-partner-universities",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "winter_programme",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    createRootDocument: false,
    linkedDocumentTypes: ["pdf"],
    programmeDetails: true,
    maxLinkedPages: 60,
  },
  {
    id: "nus-gro-summer-winter-application-guide",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Summer and Winter Application Guide",
    url: "https://www.nus.edu.sg/gro/global-programmes/summer-and-winter-programmes/i-sp-application-guide",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "summer_programme",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    // The guide explains the process, but is not itself an opportunity.
    createRootDocument: false,
    linkedDocumentTypes: ["pdf"],
    programmeDetails: false,
    maxLinkedPages: 0,
  },
  {
    id: "nus-gro-research-attachments",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Research Attachments",
    url: "https://www.nus.edu.sg/gro/global-programmes/research-attachments",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "research",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    maxLinkedPages: 4,
  },
  {
    id: "nus-gro-steer",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Global Relations - Study Trips for Engagement and EnRichment",
    url: "https://www.nus.edu.sg/gro/global-programmes/special-global-programmes/steer",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "exchange",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    maxLinkedPages: 5,
  },
  {
    id: "nus-enterprise-noc",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Enterprise - NUS Overseas Colleges",
    url: "https://enterprise.nus.edu.sg/education-programmes/nus-overseas-colleges/",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "entrepreneurship",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    maxLinkedPages: 5,
  },
  {
    id: "nus-enterprise-noc-application-info",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Enterprise - NOC Application Info",
    url: "https://enterprise.nus.edu.sg/education-programmes/nus-overseas-colleges/apply/application-info/",
    enabled: true,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "entrepreneurship",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    minScore: 3,
    maxLinkedPages: 8,
  },
  {
    id: "nus-enterprise-events-funding",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NUS Enterprise - Events and Funding",
    url: "https://enterprise.nus.edu.sg/",
    enabled: false,
    allowedHosts: NUS_HOSTS,
    defaultCategory: "entrepreneurship",
    sourceTrustBoost: 3,
    targetAudience: "nus_students",
    trustedForNusStudents: true,
    maxLinkedPages: 8,
  },
  {
    id: "govtech-student-internships",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "GovTech Student Internships",
    url: "https://www.tech.gov.sg/careers/students-and-graduates/internships/",
    enabled: true,
    allowedHosts: GOVTECH_HOSTS,
    defaultCategory: "internship",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 4,
  },
  {
    id: "dsta-internships",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "DSTA Internships",
    url: "https://www.dsta.gov.sg/join-us/student/internships",
    enabled: true,
    allowedHosts: DSTA_HOSTS,
    defaultCategory: "internship",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 5,
  },
  {
    id: "dsta-brainhack",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "DSTA BrainHack",
    url: "https://www.dsta.gov.sg/brainhack",
    enabled: true,
    allowedHosts: DSTA_HOSTS,
    defaultCategory: "competition",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 4,
  },
  {
    id: "astar-scholarships-research",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "A*STAR Scholarships and Research Attachments",
    url: "https://www.a-star.edu.sg/scholarships",
    enabled: true,
    allowedHosts: ASTAR_HOSTS,
    defaultCategory: "scholarship",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 5,
  },
  {
    id: "sginnovate-career-development",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "SGInnovate Career Development and Jobs",
    url: "https://www.sginnovate.com/career-development-jobs",
    enabled: true,
    allowedHosts: SGINNOVATE_HOSTS,
    defaultCategory: "internship",
    sourceTrustBoost: 1,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 5,
  },
  {
    id: "sginnovate-events",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "SGInnovate Events",
    url: "https://www.sginnovate.com/events",
    enabled: true,
    allowedHosts: SGINNOVATE_HOSTS,
    defaultCategory: "networking",
    sourceTrustBoost: 1,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 6,
  },
  {
    id: "nyc-programmes-grants",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "National Youth Council Programmes and Grants",
    url: "https://www.nyc.gov.sg/programmes-grants/",
    enabled: true,
    allowedHosts: NYC_HOSTS,
    defaultCategory: "community",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 6,
  },
  {
    id: "nyc-young-changemakers",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "NYC Young ChangeMakers",
    url: "https://www.nyc.gov.sg/programmes-grants/programmes/young-changemakers/",
    enabled: true,
    allowedHosts: NYC_HOSTS,
    defaultCategory: "community",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 4,
  },
  {
    id: "youth-corps-singapore",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "Youth Corps Singapore",
    url: "https://youthcorps.nyc.gov.sg/",
    enabled: true,
    allowedHosts: NYC_HOSTS,
    defaultCategory: "volunteer",
    sourceTrustBoost: 2,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 5,
  },
  {
    id: "pier71-smart-port",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "PIER71 Smart Port Challenge",
    url: "https://pier71.sg/smart-port-challenge/",
    enabled: true,
    allowedHosts: PIER71_HOSTS,
    defaultCategory: "competition",
    sourceTrustBoost: 1,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 4,
  },
  {
    id: "cybersg-tig",
    school: DEFAULT_SCHOOL,
    type: "public_web",
    name: "CyberSG TIG Collaboration Centre",
    url: "https://tig.cybersg.sg/",
    enabled: true,
    allowedHosts: CYBERSG_HOSTS,
    defaultCategory: "networking",
    sourceTrustBoost: 1,
    targetAudience: "nus_students",
    requiresNusStudentEligibility: true,
    maxLinkedPages: 5,
  },
];

export const crawlerSources = crawlerSourceConfig.map((source) => ({
  ...source,
  sourcePriority: source.sourcePriority ?? inferSourcePriority(source),
}));

export const sources = crawlerSources;
